module.exports = global.jezyki= {
    pl:{
        // formularz pieska
        imie: 'Imię',
        plec: 'Płeć',
        samiec: 'Samiec',
        samica: 'Samica',
        dataUrodzeniaFormularzPieska: 'Data urodzenia (min. wiek to 1 rok)',
        rasa: 'Rasa',
        waga: 'Waga',
        wyslij: 'Wyślij',
        // rezerwacje użytkownika
        witamy1: 'Witamy użytkowniku ',
        witamy2: ' na portalu Psiotel!',
        aktualneRezerwacje: 'Aktualne rezerwacje',
        otoAktualneRezerwacje: 'Oto twoje trwające i przyszłe rezerwacje. Te drugie możesz edytować',
        historiaRezerwacji: 'Historia rezerwacji',
        otoHistoriaRezerwacji: 'Oto historia wszystkich Twoich rezerwacji',
        dodajRezerwacje: 'Dodaj rezerwację',
        dodajRezerwacjeOpis: 'Kliknij ponizszy przycisk, aby przejść do formularza rejestracji rezerwacji',
        // formularz rezerwacji
        ladowaniePieskow: 'Ładowanie piesków, proszę czekać. Jeśli długo się nie ładuje, może to oznaczać brak piesków.',
        ladowanieRezerwacji: 'Trwa ładowanie rezerwacji. Jeżeli długo się nie ładuje, może to oznaczać brak rezerwacji',
        wybierzPieska: 'Wybierz pieska:',
        dataRozpoczecia: 'Data rozpoczęcia',
        dataZakonczenia: 'Data zakonczenia',
        pakiet: 'Pakiet',
        zwyklyPakiet: 'Zwykły',
        // edytuj pieska
        edycjaDanychPieska: 'Edycja danych pieska',
        usunPieskaZBazy: 'Usuń pieska z bazy',
        usunPieskaZBazyOpis: 'Kliknij ponoższy przycisk, aby usunąć pieska z bazy, wraz z historią jego rezerwacji.',
        przyciskUsunPieska: 'Usuń pieska',
        bladUsunPieska: 'Nie można usunąć pieska, który ma aktywne rezerwacje. Przed usunięciem anuluj jego wszystkie aktywne rezerwacje',
        // edytuj rezerwację
        aktualniePrzypisanyPiesTo: 'Aktualnie przypisany pies to: ',
        edycjaRezerwacji: 'Edycja rezerwacji',
        anulujRezerwacje: 'Anuluj rezerwację',
        anulujRezerwacjeOpis: 'Kliknij ponoższy przycisk, aby anulować rezerwację. Jeżeli aktualnie trwa i piesek nie ' +
            'został jeszcze odebrany, będą doliczane dodatkowe koszty, jak w przypadku nie odebrania pupila po zakończeniu rezerwacji.',
        // error 404
        error404tekst: 'Ojojoj! Taka strona nie istnieje!',
        // formularz użytkownika
        nazwisko: 'Nazwisko',
        dataUrodzeniaFormularzUzytkownika: 'Data urodzenia (wiek 18+)',
        ulicaNumerDomu: 'Ulica i numer domu',
        kodPocztowy: 'Kod pocztowy',
        miasto: 'Miasto',
        email: 'Adres email',
        telefon: 'Numer telefonu',
        login: 'Login (musi mieć od 2 do 30 znaków)',
        haslo: 'Hasło (musi mieć małą i dużą literę, cyfrę, znak specjalny i conajmniej 8 znaków)',
        zarejestruj: 'Zarejestruj',
        // konto użytkownika
        ladowanieDanychKonta: 'Ładowanie danych konta, proszę czekać...',
        daneKonta: 'Dane konta',
        otoDaneKonta: 'Oto dane Twojego konta. Prześlij formularz ze zmienionymi danymi, aby je zapisać.',
        pomyslnieZmienionoDane: 'Pomyślnie zmieniono dane konta!',
        usunKonto: 'Usuń konto',
        usunKontoOpis: 'Usuń swoje konto na portalu Psiotel, wraz z zarejestrowanymi psami i ich rezerwacjami',
        tejOperacjiNieDaSieCofnac: 'Tej operacji nie da się cofnąć.',
        // logowanie
        zalogujSie: 'Zaloguj się!',
        zaloguj: 'Zaloguj',
        // nagłówek
        oNas: 'O nas',
        stronaGlowna: 'Strona główna',
        // nagłówek zalogowano
        wyloguj: 'Wyloguj',
        konto: 'Konto',
        psiaki: 'Psiaki',
        rezerwacje: 'Rezerwacje',
        // o nas
        oNaszymHotelu: 'O naszym hotelu',
        oNaszymHoteluOpis: 'Nasza rodzina prowadzi Psiotel od prawie trzydziestu lat. Zaczęło się od małego zakładu, ale dziś możemy' +
            'pochwalić się opiekowaniem w sumie ponad 10 000 róznymi pupilami, które w sumie spędziły u nas prawie milion' +
            'godzin! Aktualnie nasz hotel zatrudnia ponad 100 pracowników i ma miejsce na 300 gości naraz. ' +
            'Jesteśmy dumni z tego, co robimy i mamy nadzieję, że będziemy przyjmować naszych czworonożnych ' +
            'przyjaciół jeszcze przez wiele dekad.',
        opinie: 'Opinie',
        otoOpinie: 'Oto opinie gości o naszym hotelu.',
        opiniaGosc1: 'gość z Krakowa',
        opiniaGosc2: 'gość z Berlina',
        opiniaGosc3: 'gość z Paryża',
        opiniaGosc4: 'gość z Tokio',
        // rejestracja psiaka
        ladowanieDanych: 'Ładowanie danych, proszę czekać...',
        maksymalnaLiczbaPieskow: 'Osiągnięto maksymalną liczbę piesków',
        maksymalnaLiczbaPieskowOpis1: 'Przykro nam, ale maksymalna liczba piesków jednego użytkownika aktualnie wynosi ',
        maksymalnaLiczbaPieskowOpis2:'. Nie można dodać więcej piesków',
        zarejestrujNowegoPsiaka: 'Zarejestruj nowego psiaka!',
        // pieski użytkownika
        mojePieski: 'Moje pieski',
        otoMojePieski: 'Oto twoje pieski, które zostały zarejestrowane w naszym systemie.',
        edytuj: 'Edytuj',
        nieZnalezionoPieskow: 'Nie masz jeszcze żadnych zarejestrowanych piesków.',
        dodajPieskaOpis: "Kliknij poniższy przycisk aby przejść do formularza rejestracji psiaka",
        dodajPieska: 'Dodaj pieska',
        szczegoly: 'Szczegóły',
        // rejestracja rezerwacji
        wykonajNowaRezerwacje: 'Wykonaj nową rezerwację!',
        //rejestracja użytkownika
        zarejestrujSie: 'Zarejestruj się!',
        // stopka
        kontakt: 'Kontakt',
        numerTelefonuKontakt: 'Nr telefonu',
        skrzynkaPocztowa: 'Skrzynka pocztowa',
        adresKontaktowy: 'Adres',
        partnerzy: 'Partnerzy',
        dostawcaKarmy: 'Dostawca karmy',
        dostawcaPoduszek: 'Dostawca poduszek',
        dostawcaObroz: 'Dostawca intelignetnych obróż',
        cytat: 'Pieskie życie może być piękne!',
        // strona główna
        witamyWPsiotelu: 'Witamy w Psiotelu, najlepszym hotelu dla psów w Nienacku!',
        witamyWPsioteluOpis: 'Zostaw pod naszą opieką swojego czworonożnego PSIAciela, ' +
            'gdy nie możesz zabrać go ze sobą w trakcie wyjazdu. Zadbamy o niego ' +
            'według najwyższych standardów i będzie zadowolony czekał na Twój powrót!',
        oferowanePrzezNasUslugi: 'Oferowane przez nas usługi to',
        usluga1: 'Całodobowa opieka weterynaryjna',
        usluga2: 'Wygodne i przytulne kojce, w których psy zostają tylko na noc.',
        usluga3: 'Wielki plac zabaw, na którym socjalizują sie z innymi pieskami pod stałym okiem doświadczonych opiekunów.',
        usluga4: 'Obroże wykrywające nastrój na podstawie odczytów biometrycznych, pozwalające reagować natychmiast na lęk i dyskomfort.',
        usluga5: 'Inteligentne zabawki stymulujące pieski m. in. dźwiękami, światłami, wibracjami i zapachami.',
        usluga6: 'Najwyższej jakości karma z uwzględnieniem preferencji, nietolerancji i alergii pokarmowej.',
        usluga7: 'Psie spa z m. in. myciem, czesaniem, strzyżeniem i masażami.',
        naszePakiety: 'Nasze pakety',
        naszePakietyOpis: 'Usługi różnią się od wybranego pakietu, ale każdy z nich zapewnia, że Twój czworonożny przyjaciel ' +
            'będzie pod profesjonalną opieką. Poniżej znajduje się rozpiska pakietów i oferowanych przez nie usług.',
        tabelkaUsluga: 'Usługa',
        tabelkaPakietZwykly: 'Pakiet zwykły',
        tabelkaPakietVIP: 'Pakiet VIP',
        tabelkaOpieka: 'Opieka weterynaryjna',
        takCaps: 'TAK',
        nieCaps: 'NIE',
        tabelkaKojce: 'Kojce',
        tabelkaKojceOpis1: 'Wygodne z posłaniem i lampkami',
        tabelkaKojceOpis2: 'Luksusowe z dodatkowymi poduszkami i izolacją dźwięku',
        placZabaw: 'Plac zabaw',
        placZabawOpis1: 'Duży, bezpieczny, na zewnątrz i wewnątrz',
        placZabawOpis2: 'Dodatkowy dostęp do basenu',
        tabelkaObroze: 'Obroże wykrywające nastrój',
        tabelkaZabawki: 'Inteligentne zabawki',
        tabelkaJakoscKarmy: 'Jakosc karmy',
        tabelkaJakoscKarmyWysoka: 'Wysoka',
        tabelkaJakoscKarmyNajwyzsza: 'Najwyższa',
        tabelkaPsieSpa: 'Psie spa',
        // tabelka rezerwacji
        idRezerwacji: 'Id Rezerwacji',
        imiePsa: 'Imię psa',
        statusRezerwacji: 'Status rezerwacji',
        ktoraStrona1: 'Strona ',
        ktoraStrona2: ' z ',
        poprzedniaStrona: 'Poprzednia strona',
        nastepnaStrona: 'Następna strona',
        // tabelki
        pustaTabelka: 'Pusta tabelka :(',
        dataUrodzenia: 'Data urodzenia',
    },
    en:{
        // formularz pieska
        imie: 'Name',
        plec: 'Sex',
        samiec: 'Male',
        samica: 'Female',
        dataUrodzeniaFormularz: 'Date of birth (min. age is 1 year)',
        rasa: 'Breed',
        waga: 'Weight',
        wyslij: 'Send',
        // rezerwacje użytkownika
        witamy1: 'Welcome user ',
        witamy2: ' on Psiotel!',
        aktualneRezerwacje: 'Active reservations',
        otoAktualneRezerwacje: 'Here are Your current and incoming reservations',
        historiaRezerwacji: 'Reservation history',
        otoHistoriaRezerwacji: 'Here is the history of all Your reservations. You can edit the latter.',
        dodajRezerwacje: 'Add a reservation',
        dodajRezerwacjeOpis: 'Click the button below to go to the reservation registration form',
        // formularz rezerwacji
        ladowaniePieskow: 'Loading dogs, please wait. If it takes a long time to load, it may mean there are no dogs.',
        ladowanieRezerwacji: 'Loading reservations, please wait. If it takes a long time to load, it may mean there are no reservations.',
        wybierzPieska: 'Select a dog:',
        dataRozpoczecia: 'Begin date',
        dataZakonczenia: 'End date',
        pakiet: 'Bundle',
        zwyklyPakiet: 'Standard',
        // edytuj pieska
        edycjaDanychPieska: 'Edit data of dog ',
        usunPieskaZBazy: 'Remove dog \'s data from the database',
        usunPieskaZBazyOpis: 'Click button below to remove it\'s data from the database and it\'s reservation history.',
        przyciskUsunPieska: 'Delete dog',
        bladUsunPieska: 'Cannot remove data of a dog with active reserwations. Before deleting a dog cancel all it\'s active reservations.',
        // edytuj rezerwację
        aktualniePrzypisanyPiesTo: 'The currently assigned dog is: ',
        edycjaRezerwacji: 'Edit reservation',
        anulujRezerwacje: 'Cancel reservation',
        anulujRezerwacjeOpis: 'Click the button below to cancel your reservation. If it is currently ongoing and your dog has not been picked up yet, ' +
            'additional costs will apply, as in the case of not picking up your pet after the reservation has ended.',
        // error 4040
        error404tekst: 'Whoops! That site does not exist!',
        // rejestracja użytkownika
        nazwisko: 'Surname',
        dataUrodzeniaFormularzUzytkownika: 'Birth date (age 18+)',
        ulicaNumerDomu: 'Street and house number',
        kodPocztowy: 'Zip code',
        miasto: 'City',
        email: 'Email address',
        telefon: 'Phone number',
        login: 'Login (must be between 2 and 30 characters long)',
        haslo: 'Password (must have lowercase and uppercase letters, a number, a special character and at least 8 characters)',
        zarejestruj: 'Register',
        // konto użytkownika
        ladowanieDanychKonta: 'Loading account data, please wait...',
        daneKonta: 'Account details',
        otoDaneKonta: 'Here are your account details. Submit the form with your changed details to save them.',
        pomyslnieZmienionoDane: 'Account details changed successfully!',
        usunKonto: 'Delete account',
        usunKontoOpis: 'Delete your account on the Psiotel portal, along with your registered dogs and their reservations. ',
        tejOperacjiNieDaSieCofnac: 'This operation cannot be undone.',
        // logowanie
        zalogujSie: 'Log in!',
        zaloguj: 'Log in',
        // nagłówek
        oNas: 'About us',
        stronaGlowna: 'Main page',
        wyloguj: 'Log out',
        konto: 'Account',
        psiaki: 'Dogs',
        rezerwacje: 'Reservations',
        // o nas
        oNaszymHotelu: 'About our hotel',
        oNaszymHoteluOpis: 'Our family has been running Psiotel for almost thirty years. It started as a small business, ' +
            'but today we can boast of having cared for over 10,000 different pets, who have spent almost a million hours with us!' +
            'Our hotel currently employs over 100 people and can accommodate 300 guests at a time.' +
            'We are proud of what we do and hope that we will continue to welcome our four-legged friends for many decades to come.',
        opinie: 'Reviews',
        otoOpinie: 'Here are what guests say about our hotel.',
        opiniaGosc1: 'a guest from Cracow',
        opiniaGosc2: 'a guest from Berlin',
        opiniaGosc3: 'a guest from Paris',
        opiniaGosc4: 'a guest from Tokio',
        // rejestracja psiaka
        ladowanieDanych: 'Loading data, please wait...',
        maksymalnaLiczbaPieskow: "Maximum number of dogs reached",
        maksymalnaLiczbaPieskowOpis1: 'We are sorry, but the maximum number of dogs per user is currently ',
        maksymalnaLiczbaPieskowOpis2:'. Cannot add more dogs',
        zarejestrujNowegoPsiaka: 'Register a new dog!',
        // pieski użytkownika
        mojePieski: 'My dogs',
        otoMojePieski: 'Here are your dogs that have been registered in our system.',
        edytuj: 'Edit',
        nieZnalezionoPieskow: "You do not have any registered dogs yet.",
        dodajPieskaOpis: "Click the button below to go to the dog registration form.",
        dodajPieska: 'Add a dog',
        szczegoly: 'Details',
        // rejestracja rezerwacji
        wykonajNowaRezerwacje: 'Make a new reservation!!',
        // rejestracja użytkownika
        zarejestrujSie: 'Register on our website!',
        // stopka
        kontakt: 'Contact',
        numerTelefonuKontakt: 'Phone number',
        skrzynkaPocztowa: 'Post box',
        adresKontaktowy: 'Address',
        partnerzy: 'Partners',
        dostawcaKarmy: 'Feed supplier',
        dostawcaPoduszek: 'Pillow supplier',
        dostawcaObroz: 'Smart collars supplier',
        cytat: 'A dog\'s life can be beautiful!',
        // strona główna
        witamyWPsiotelu: 'Welcome to Psiotel, the best dog hotel in Nienack!',
        witamyWPsioteluOpis: 'Leave your four-legged friend in our care when you can\'t take it with you on your trip. ' +
            'We will take care of it according to the highest standards and it will be happy and waiting for your return!',
        oferowanePrzezNasUslugi: 'The services we offer are:',
        usluga1: '24-hour veterinary care.',
        usluga2: 'Comfortable and cozy kennels where dogs stay only at night.',
        usluga3: 'A large playground where they socialize with other dogs under the constant supervision of experienced caregivers.',
        usluga4: 'Collars that detect mood based on biometric readings, allowing you to respond immediately to anxiety and discomfort.',
        usluga5: 'Smart toys that stimulate dogs with sounds, lights, vibrations and scents.',
        usluga6: 'Top quality food taking into account preferences, intolerances and food allergies.',
        usluga7: 'Dog spa including washing, brushing, cutting and massages.',
        naszePakiety: 'Our bundles',
        naszePakietyOpis: 'The services vary depending on the package you choose, but each one ensures that your four-legged friend ' +
            'will be under professional care. Below is a list of the packages and the services they offer.',
        tabelkaUsluga: 'Service',
        tabelkaPakietZwykly: 'Standard bundle',
        tabelkaPakietVIP: 'VIP bundle',
        tabelkaOpieka: 'Veterinary care',
        takCaps: 'YES',
        nieCaps: 'NIE',
        tabelkaKojce: 'Kennels',
        tabelkaKojceOpis1: 'Comfortable with bedding and lights',
        tabelkaKojceOpis2: 'Luxurious with extra cushions and sound insulation',
        placZabaw: 'Playground',
        placZabawOpis1: 'Large, safe, outside and inside',
        placZabawOpis2: 'Dodatkowy dostęp do basenu',
        tabelkaObroze: 'Mood detecting collars',
        tabelkaZabawki: 'Smart toys',
        tabelkaJakoscKarmy: 'Food quality',
        tabelkaJakoscKarmyWysoka: 'High',
        tabelkaJakoscKarmyNajwyzsza: 'The highest',
        tabelkaPsieSpa: 'Dog spa',
        // tabelka rezerwacji
        idRezerwacji: 'Reservation id',
        imiePsa: 'Dog name',
        statusRezerwacji: 'Reservation status',
        ktoraStrona1: 'Page ',
        ktoraStrona2: ' of ',
        poprzedniaStrona: 'Previous page',
        nastepnaStrona: 'Next page',
        // tabelki
        pustaTabelka: 'Empty table :(',
        dataUrodzenia: 'Date of birth'
    }
}